### ISSUE TITLE
PT nightly optim failing both on cpu and gpu

### ISSUE THREAD

**Issue by msaroufim** [pytorch/ao#1067]
```
FAILED test/prototype/test_low_bit_optim.py::TestOptim::test_optim_smoke_optim_name_AdamW8bit_bfloat16_device_cuda - torch._dynamo.exc.TorchRuntimeError: Failed running call_method lerp(*(OptimState8bit(signed=True, block_size=256, shape=(256, 32), device=cuda:0, requires_grad=False), FakeTensor(..., device='cuda:0', size=(256, 32), dtype=torch.bfloat16), 0.09999999999999998), **{}):
  expected dtype torch.float32 for `end`, but got dtype torch.bfloat16
  
  from user code:
     File "/opt/conda/envs/venv/lib/python3.9/site-packages/torchao/prototype/low_bit_optim/adam.py", line 136, in single_param_adam
      new_exp_avg = exp_avg.lerp(grad, 1 - beta1)
  
  Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
  
  
  You can suppress this exception and fall back to eager by setting:
      import torch._dynamo
      torch._dynamo.config.suppress_errors = True
  
  
  To execute this test, run the following from the base repo dir:
      python test/prototype/test_low_bit_optim.py TestOptim.test_optim_smoke_optim_name_AdamW8bit_bfloat16_device_cuda
  
  This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
  Traceback (most recent call last):
  FAILED test/prototype/test_low_bit_optim.py::TestOptim::test_optim_smoke_optim_name_AdamWFp8_bfloat16_device_cpu - torch._dynamo.exc.TorchRuntimeError: Failed running call_method lerp(*(OptimStateFp8(block_size=256, shape=(256, 32), device=cpu, requires_grad=False), FakeTensor(..., size=(256, 32), dtype=torch.bfloat16), 0.09999999999999998), **{}):
  expected dtype torch.float32 for `end`, but got dtype torch.bfloat16
  
  from user code:
    File "/home/ec2-user/actions-runner/_work/ao/ao/test-infra/.github/scripts/run_with_env_secrets.py", line 102, in <module>
      main()
    File "/home/ec2-user/actions-runner/_work/ao/ao/test-infra/.github/scripts/run_with_env_secrets.py", line 98, in main
      run_cmd_or_die(f"docker exec -t {container_name} /exec")
    File "/home/ec2-user/actions-runner/_work/ao/ao/test-infra/.github/scripts/run_with_env_secrets.py", line 39, in run_cmd_or_die
      raise RuntimeError(f"Command {cmd} failed with exit code {exit_code}")
  RuntimeError: Command docker exec -t e74d66a60a6291d2f59d9c62d0cc410d78f62234cd213495bb69f85b4691ff43 /exec failed with exit code 1
     File "/opt/conda/envs/venv/lib/python3.9/site-packages/torchao/prototype/low_bit_optim/adam.py", line 136, in single_param_adam
      new_exp_avg = exp_avg.lerp(grad, 1 - beta1)
  
  Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
  
  
  You can suppress this exception and fall back to eager by setting:
      import torch._dynamo
      torch._dynamo.config.suppress_errors = True
  
  
  To execute this test, run the following from the base repo dir:
      python test/prototype/test_low_bit_optim.py TestOptim.test_optim_smoke_optim_name_AdamWFp8_bfloat16_device_cpu
  
  This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
  === 10 failed, 1639 passed, 380 skipped, 123 warnings in 3083.48s (0:51:23) ====
  Error: Process completed with exit code 1.
```

**Comment by gau-nernst** [comment]
I think I know how to fix this. torch.compile/tensor subclass used to not check dtype compatibility in an op I think. In this case, it is `torch.lerp(normal_bf16_tensor, subclass_fp32_tensor)` because I always use FP32 apperance dtype for optim state (tensor subclass). Will push a fix later.
