### ISSUE TITLE
Cannot import torchao because AttributeError: module 'torch' has no attribute 'float8_e4m3fn'

### ISSUE THREAD

**Issue by LukeLIN-web** [pytorch/ao#1095]
I cannot even run` transformers-cli env`

```
Traceback (most recent call last):
  File "/usr/local/bin/transformers-cli", line 5, in <module>
    from transformers.commands.transformers_cli import main
  File "/usr/local/lib/python3.10/dist-packages/transformers/commands/transformers_cli.py", line 24, in <module>
    from .run import RunCommand
  File "/usr/local/lib/python3.10/dist-packages/transformers/commands/run.py", line 17, in <module>
    from ..pipelines import Pipeline, PipelineDataFormat, get_supported_tasks, pipeline
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/__init__.py", line 77, in <module>
    from .text_to_audio import TextToAudioPipeline
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/text_to_audio.py", line 22, in <module>
    from ..models.speecht5.modeling_speecht5 import SpeechT5HifiGan
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/speecht5/modeling_speecht5.py", line 36, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 58, in <module>
    from .quantizers import AutoHfQuantizer, HfQuantizer
  File "/usr/local/lib/python3.10/dist-packages/transformers/quantizers/__init__.py", line 14, in <module>
    from .auto import AutoHfQuantizer, AutoQuantizationConfig
  File "/usr/local/lib/python3.10/dist-packages/transformers/quantizers/auto.py", line 42, in <module>
    from .quantizer_torchao import TorchAoHfQuantizer
  File "/usr/local/lib/python3.10/dist-packages/transformers/quantizers/quantizer_torchao.py", line 35, in <module>
    from torchao.quantization import quantize_
  File "/usr/local/lib/python3.10/dist-packages/torchao/__init__.py", line 31, in <module>
    from torchao.quantization import (
  File "/usr/local/lib/python3.10/dist-packages/torchao/quantization/__init__.py", line 7, in <module>
    from .smoothquant import *  # noqa: F403
  File "/usr/local/lib/python3.10/dist-packages/torchao/quantization/smoothquant.py", line 18, in <module>
    from .utils import (
  File "/usr/local/lib/python3.10/dist-packages/torchao/quantization/utils.py", line 12, in <module>
    from torchao.quantization.quant_primitives import (
  File "/usr/local/lib/python3.10/dist-packages/torchao/quantization/quant_primitives.py", line 65, in <module>
    torch.float8_e4m3fn,
  File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 1774, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute 'float8_e4m3fn'
[2024-10-16 19:06:55,672] torch._dynamo.utils: [INFO] TorchDynamo compilation metrics:
Function    Runtimes (s)
----------  --------------
```

My env
```
cuda 12.2
titan 2080 ti 
torch                     2.1.0a0+29c30b1
torch-tensorrt            2.0.0.dev0
torchao                   0.5.0
torchdata                 0.7.0a0
torchtext                 0.16.0a0
torchvision               0.16.0a0
tornado                   6.3.2
tqdm                      4.65.0
traitlets                 5.9.0
transformer-engine        0.11.0+3f01b4f
transformers              4.45.2
treelite                  3.2.0
treelite-runtime          3.2.0
triton                    2.1.0+440fd1b
typer                     0.9.0
types-dataclasses         0.6.6
typing_extensions         4.7.1
ucx-py                    0.32.0
uff                       0.6.9
urllib3                   1.26.16
wasabi                    1.1.2
wcwidth                   0.2.6
webencodings              0.5.1
Werkzeug                  2.3.6
wheel                     0.41.1
xdoctest                  1.0.2
xgboost                   1.7.5
yarl                      1.9.2
zict                      3.0.0
zipp                      3.16.2
```

**Comment by LukeLIN-web** [comment]
Upgrade torch to 2.4.1 can solve it.

`pip install --upgrade torch torchvision`
