### ISSUE TITLE
Add codebook (look up table based) quantization flow in torchao

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/ao#1195]
Similar to affine quantization, we can implement codebook or look up table based quantization, which is another popular type of quantization, especially for lower bits like 4 bits or below (used in https://github.com/Vahe1994/AQLM, https://arxiv.org/abs/2402.04396 etc.). We can start with post training quantization and use k-means clustering to find the codebook / lookup table. You can check out https://github.com/pytorch/ao/issues/391 for the overall structure of torchao stack. Reference code for k-means can be found [here](https://github.com/apple/coremltools/blob/40f6705a6a4c5ef1a616f01b444f1d6e5a0c1f59/coremltools/optimize/torch/_utils/k_means.py#L1008).

After this we can also add more support for the advanced algorithms mentioned above.

API
```
quantize_(model, codebook_weight_only(dtype=torch.uint4))
```

Implementation details:
* [PR1] Ops
  * quantize_codebook(tensor, codebook)
  * dequantize_codebook(tensor, codebook)
* [PR2] Tensor Subclass
  * CodebookQuantizedTensor (similar to AffineQuantizedTensor)
    * clustering algorithm can be implemented in from_float function

Needs to flesh out the details of args etc. but can be done in the PR. I'd suggest to gradually add things and gather feedback.

Code Location: add a `codebook` folder under https://github.com/pytorch/ao/tree/main/torchao/prototype/quantization

**Comment by malinjawi** [comment]
Hey @jerryzh168 I am new to torchao but this sounds like an issue I would want to investigate with my partner @harthi7. We will take a look and let you know how it goes. Cheers!

**Comment by DerekLiu35** [comment]
Hi, I am also new to torchao and I would like to do this issue?

**Comment by pawarmanasi07** [comment]
Hi! I'm interested in contributing to the implementation of the codebook quantization. Would it be helpful if I worked on [specific area - e.g., additional test cases, AQLM support, etc.]? Happy to coordinate with @DerekLiu35 to avoid duplicating effort.

**Comment by jerryzh168** [comment]
I think the two immediate things are adding AQLM support and speedup. Adding AQLM in torchao will be a bit more convenient for users compared to using AQLM repo and then convert I think

**Comment by pawarmanasi07** [comment]
Great! Let me know what I can start with.

**Comment by DerekLiu35** [comment]
I'll focus on speeding up token generation, can coordinate more if @pawarmanasi07 also wants to work on that.

**Comment by pawarmanasi07** [comment]
I can help with that!

**Comment by pawarmanasi07** [comment]
@DerekLiu35 Could you share your thoughts on which aspects of the dequantization kernels from AQLM we should focus on first? We could divide up different parts of the optimization work between us?

**Comment by DerekLiu35** [comment]
I think we can focus on [1x16 group size cuda kernels](https://github.com/Vahe1994/AQLM/blob/main/inference_lib/src/aqlm/inference_kernels/cuda_kernel.cpp) and [triton (as fallback)](https://github.com/Vahe1994/AQLM/blob/main/inference_lib/src/aqlm/inference_kernels/triton_kernel.py). we could divide optimization work by one of us focusing on forward pass kernels and the other on backward pass kernels, though I'm not sure why you need backward pass kernels. we could also split by different kernels like 1x16 group size and 1x1 group size (no reference cuda kernels in AQLM). I'm not sure what the best way to divide work between us though. I'll probably start with 1x16 forward pass kernel

**Comment by pawarmanasi07** [comment]
Sounds good! I think focusing on the 1x16 group size kernels makes sense as a starting point. I can work on the 1x1 group size kernels while you tackle the 1x16 forward pass implementation. 

For the backward pass kernels - you raise a good point about whether they're necessary. Since this is post-training quantization, we likely don't need backward pass optimization unless we're planning to support fine-tuning scenarios?

**Comment by pawarmanasi07** [comment]
Hi @DerekLiu35 and @jerryzh168, just to confirm my tasks - I'll be focusing on optimizing the dequantization for 1x1 group size using Triton (not CUDA/C++). This involves:

Creating optimized Triton kernel for 1x1 dequantization
Adding benchmarks and tests
Integrating with the existing codebase

While Derek focuses on the 1x16 forward pass kernel implementation. 

Is this the correct understanding of the work division?

**Comment by pawarmanasi07** [comment]
However would it make more sense to start with Triton implementation for 1x1 first (since we need it as a fallback anyway)
then evaluate if we need CUDA implementation based on performance?

**Comment by DerekLiu35** [comment]
Yeah I think that would make sense to start with triton fallaback first

**Comment by LucasHaug** [comment]
Not sure if this is the right place to post this, but I was testing the CodebookQuantizedTensor and noticed a problem. I can't say if it's easy to fix or if it's a priority, but I thought it would be better to report it.

I was trying to set the the `requires_grad` of the tensor to `True` but as the codes are unit, they can't require gradients.

For example:

```python
import torch
from torchao.prototype.quantization.codebook.codebook_quantized_tensor import CodebookQuantizedTensor

input_tensor = torch.randn(1024, 1024,  device='cuda')

block_size = (1, 1)
code_dtype = torch.uint4

quantized_tensor = CodebookQuantizedTensor.from_float(input_tensor, block_size, code_dtype, scale_block_size=32)

quantized_tensor.requires_grad_(True)
```

Results in:

```bash
Traceback (most recent call last):
  File "/home/haug/test.py", line 11, in <module>
    quantized_tensor.requires_grad_(True)
  File "/home/haug/ao/torchao/prototype/quantization/codebook/codebook_quantized_tensor.py", line 225, in requires_grad_
    self.codes.requires_grad_(requires_grad)
  File "/home/haug/ao/torchao/utils.py", line 436, in _dispatch__torch_function__
    return func(*args, **kwargs)
RuntimeError: only Tensors of floating point dtype can require gradients
```

**Comment by jerryzh168** [comment]
thanks for trying this out @LucasHaug, yeah codebook quant is inference only right now, we should definitely support training as well, let me add this to the task list.

for training we might need a different flow, but concrete guideline is still in discussion. cc @vkuzo @andrewor14

**Comment by mostafaelhoushi** [comment]
I have been in discussion with @jcaip about integrating a 1x1 codebook quantization algorithm (for a paper that sould be on arxiv soon) as well as kernel into torchao and just noticed the discussions in this PR:
- the quantization algorithm could be implemented by modifying https://github.com/pytorch/ao/blob/b2fb664f4be31170376d6b3594037e29b21947bf/torchao/prototype/quantization/codebook/codebook_ops.py#L148
- the kernel we have is based on tinygemm and implemented by @wickedfoo. It can be added as an additional kernel to the one by @DerekLiu35 in #1607
