### ISSUE TITLE
Issue with multi-dimensional mesh

### ISSUE THREAD

**Issue by mayank31398** [pytorch/ao#1411]
Issue when using multi-dimensional mesh with FSDP-2 in combination with FP8 tensors.
error:
```shell
[rank0]: Traceback (most recent call last):
[rank0]:   File "/u/mayank98/scratch/tmp1/dolomite-engine/a.py", line 42, in <module>
[rank0]:     y = model(x)
[rank0]:         ^^^^^^^^
[rank0]:   File "/u/mayank98/miniconda3/envs/new-ai/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/u/mayank98/miniconda3/envs/new-ai/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1845, in _call_impl
[rank0]:     return inner()
[rank0]:            ^^^^^^^
[rank0]:   File "/u/mayank98/miniconda3/envs/new-ai/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1772, in inner
[rank0]:     args_kwargs_result = hook(self, args, kwargs)  # type: ignore[misc]
[rank0]:                          ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/u/mayank98/miniconda3/envs/new-ai/lib/python3.11/site-packages/torch/distributed/fsdp/_fully_shard/_fsdp_state.py", line 71, in fsdp_hook_wrapper
[rank0]:     return torch._dynamo.disable(func, recursive=True)(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/u/mayank98/miniconda3/envs/new-ai/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 744, in _fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/u/mayank98/miniconda3/envs/new-ai/lib/python3.11/site-packages/torch/distributed/fsdp/_fully_shard/_fsdp_state.py", line 239, in _pre_forward
[rank0]:     args, kwargs = self._fsdp_param_group.pre_forward(module, args, kwargs)
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/u/mayank98/miniconda3/envs/new-ai/lib/python3.11/site-packages/torch/distributed/fsdp/_fully_shard/_fsdp_param_group.py", line 334, in pre_forward
[rank0]:     self.unshard(self.unshard_async_op)
[rank0]:   File "/u/mayank98/miniconda3/envs/new-ai/lib/python3.11/site-packages/torch/distributed/fsdp/_fully_shard/_fsdp_param_group.py", line 263, in unshard
[rank0]:     self._all_gather_result = foreach_all_gather(
[rank0]:                               ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/u/mayank98/miniconda3/envs/new-ai/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/u/mayank98/miniconda3/envs/new-ai/lib/python3.11/site-packages/torch/distributed/fsdp/_fully_shard/_fsdp_collectives.py", line 139, in foreach_all_gather
[rank0]:     param_all_gather_inputs = _get_param_all_gather_inputs(fsdp_params)
[rank0]:                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/u/mayank98/miniconda3/envs/new-ai/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/u/mayank98/miniconda3/envs/new-ai/lib/python3.11/site-packages/torch/distributed/fsdp/_fully_shard/_fsdp_collectives.py", line 217, in _get_param_all_gather_inputs
[rank0]:     param_all_gather_inputs[i] = fsdp_param.all_gather_inputs
[rank0]:                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/u/mayank98/miniconda3/envs/new-ai/lib/python3.11/site-packages/torch/distributed/fsdp/_fully_shard/_fsdp_param.py", line 705, in all_gather_inputs
[rank0]:     ) = sharded_local_tensor.fsdp_pre_all_gather(self.shard_mesh)
[rank0]:                                                  ^^^^^^^^^^^^^^^
[rank0]:   File "/u/mayank98/miniconda3/envs/new-ai/lib/python3.11/site-packages/torch/distributed/fsdp/_fully_shard/_fsdp_param.py", line 796, in shard_mesh
[rank0]:     return mesh[mesh.mesh_dim_names[-1]]
[rank0]:            ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/u/mayank98/miniconda3/envs/new-ai/lib/python3.11/site-packages/torch/distributed/device_mesh.py", line 713, in __getitem__
[rank0]:     slice_mesh_dims = _mesh_resources._get_slice_mesh_dims(
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/u/mayank98/miniconda3/envs/new-ai/lib/python3.11/site-packages/torch/distributed/device_mesh.py", line 296, in _get_slice_mesh_dims
[rank0]:     raise RuntimeError("Cannot create a submesh from a submesh.")
```

code to reproduce:
```python
from torch.distributed._composable.fsdp import fully_shard
from torch.distributed.device_mesh import init_device_mesh
import torch
from torchao.float8 import (
    CastConfig,
    Float8LinearConfig,
    ScalingType,
    convert_to_float8_training,
)


class M(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.l = torch.nn.Linear(2, 2)

    def forward(self, x):
        return self.l(x)
    

mesh = init_device_mesh("cuda", (2, 2, 2), mesh_dim_names=("ddp", "fsdp", "abcd"))

with torch.device(torch.cuda.current_device()):
    model = M()
    x = torch.randn(2, 2, device=torch.cuda.current_device())

model = convert_to_float8_training(
    model,
    config=Float8LinearConfig(
        enable_fsdp_float8_all_gather=True,
        cast_config_input=CastConfig(scaling_type=ScalingType("dynamic")),
        cast_config_weight=CastConfig(scaling_type=ScalingType("dynamic")),
        cast_config_grad_output=CastConfig(scaling_type=ScalingType("dynamic")),
        force_recompute_fp8_weight_in_bwd=True,
    ),
    module_filter_fn=lambda mod, fqn: fqn != "output",
)
model = fully_shard(model, mesh=mesh["ddp", "fsdp"])

y = model(x)
```

Note that this issue can be resolved if we remove the dimension `abcd` in mesh or by setting `enable_fsdp_float8_all_gather=False`.

**Comment by weifengpy** [comment]
dicussing device mesh slicing here https://github.com/pytorch/pytorch/issues/143194#issuecomment-2544179485

**Comment by mayank31398** [comment]
closing since this is fixed
