### ISSUE TITLE
LLaMA3 WoQ quantization benchmark with torch.compile seems to be broken

### ISSUE THREAD

**Issue by sanchitintel** [pytorch/ao#601]
### Summary
Hi, with the main branch of PyTorch & torchao, I tried to run the [LLaMA3 int8 WoQ benchmark](https://github.com/pytorch/ao/blob/main/torchao/_models/llama/benchmarks.sh) (with CPU, but I suspect CUDA would run into the same issue). Please confirm if it's a known issue. Thanks!

#### Command used
```
python generate.py --checkpoint_path $CHECKPOINT_PATH/$MODEL_REPO/model.pth  --compile --quantization int8wo
```
Eager mode (not using  `--compile` argument) worked.

### Error

```
Using device=cpu
Loading model ...
Time to load model: 35.29 seconds
Compiling Model
/usr/lib/python3.10/contextlib.py:103: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
  self.gen = func(*args, **kwds)
Traceback (most recent call last):
  File "torchao/torchao/_models/llama/generate.py", line 348, in <module>
    main(
  File "torchao/torchao/_models/llama/generate.py", line 271, in main
    y = generate(
  File "torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "torchao/torchao/_models/llama/generate.py", line 117, in generate
    generated_tokens, _ = decode_n_tokens(model, next_token.view(1, -1), input_pos, max_new_tokens - 1, callback=callback, **sampling_kwargs)
  File "torchao/torchao/_models/llama/generate.py", line 68, in decode_n_tokens
    next_token, next_prob = decode_one_token(
  File "torch/_dynamo/eval_frame.py", line 464, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 1224, in __call__
    return self._torchdynamo_orig_callable(
  File "torch/_dynamo/convert_frame.py", line 514, in __call__
    return _compile(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "torch/_dynamo/convert_frame.py", line 896, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "torch/_dynamo/convert_frame.py", line 662, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
  File "torch/_utils_internal.py", line 85, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
  File "torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 697, in _compile_inner
    out_code = transform_code_object(code, transform)
  File "torch/_dynamo/bytecode_transformation.py", line 1322, in transform_code_object
    transformations(instructions, code_options)
  File "torch/_dynamo/convert_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 631, in transform
    tracer.run()
  File "torch/_dynamo/symbolic_convert.py", line 2722, in run
    super().run()
  File "torch/_dynamo/symbolic_convert.py", line 957, in run
    while self.step():
  File "torch/_dynamo/symbolic_convert.py", line 869, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 557, in wrapper
    return inner_fn(self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 1564, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "torch/_dynamo/symbolic_convert.py", line 804, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "torch/_dynamo/variables/lazy.py", line 156, in realize_and_forward
    return getattr(self.realize(), name)(*args, **kwargs)
  File "torch/_dynamo/variables/nn_module.py", line 899, in call_function
    return variables.UserFunctionVariable(fn, source=source).call_function(
  File "torch/_dynamo/variables/functions.py", line 322, in call_function
    return super().call_function(tx, args, kwargs)
  File "torch/_dynamo/variables/functions.py", line 106, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 810, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 2937, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 3053, in inline_call_
    tracer.run()
  File "torch/_dynamo/symbolic_convert.py", line 957, in run
    while self.step():
  File "torch/_dynamo/symbolic_convert.py", line 869, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 557, in wrapper
    return inner_fn(self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 1564, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "torch/_dynamo/symbolic_convert.py", line 804, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "torch/_dynamo/variables/nn_module.py", line 899, in call_function
    return variables.UserFunctionVariable(fn, source=source).call_function(
  File "torch/_dynamo/variables/functions.py", line 322, in call_function
    return super().call_function(tx, args, kwargs)
  File "torch/_dynamo/variables/functions.py", line 106, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 810, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 2937, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 3053, in inline_call_
    tracer.run()
  File "torch/_dynamo/symbolic_convert.py", line 957, in run
    while self.step():
  File "torch/_dynamo/symbolic_convert.py", line 869, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 557, in wrapper
    return inner_fn(self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 1564, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "torch/_dynamo/symbolic_convert.py", line 804, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "torch/_dynamo/variables/lazy.py", line 156, in realize_and_forward
    return getattr(self.realize(), name)(*args, **kwargs)
  File "torch/_dynamo/variables/nn_module.py", line 899, in call_function
    return variables.UserFunctionVariable(fn, source=source).call_function(
  File "torch/_dynamo/variables/functions.py", line 322, in call_function
    return super().call_function(tx, args, kwargs)
  File "torch/_dynamo/variables/functions.py", line 106, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 810, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 2937, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 3053, in inline_call_
    tracer.run()
  File "torch/_dynamo/symbolic_convert.py", line 957, in run
    while self.step():
  File "torch/_dynamo/symbolic_convert.py", line 869, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 557, in wrapper
    return inner_fn(self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 1564, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "torch/_dynamo/symbolic_convert.py", line 804, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "torch/_dynamo/variables/lazy.py", line 156, in realize_and_forward
    return getattr(self.realize(), name)(*args, **kwargs)
  File "torch/_dynamo/variables/nn_module.py", line 899, in call_function
    return variables.UserFunctionVariable(fn, source=source).call_function(
  File "torch/_dynamo/variables/functions.py", line 322, in call_function
    return super().call_function(tx, args, kwargs)
  File "torch/_dynamo/variables/functions.py", line 106, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 810, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 2937, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 3053, in inline_call_
    tracer.run()
  File "torch/_dynamo/symbolic_convert.py", line 957, in run
    while self.step():
  File "torch/_dynamo/symbolic_convert.py", line 869, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 1706, in LOAD_ATTR
    self._load_attr(inst)
  File "torch/_dynamo/symbolic_convert.py", line 1696, in _load_attr
    result = BuiltinVariable(getattr).call_function(
  File "torch/_dynamo/variables/builtin.py", line 981, in call_function
    return handler(tx, args, kwargs)
  File "torch/_dynamo/variables/builtin.py", line 862, in builtin_dipatch
    rv = fn(tx, args, kwargs)
  File "torch/_dynamo/variables/builtin.py", line 780, in call_self_handler
    result = self_handler(tx, *args, **kwargs)
  File "torch/_dynamo/variables/builtin.py", line 1719, in call_getattr
    return obj.var_getattr(tx, name)
  File "torch/_dynamo/variables/nn_module.py", line 1120, in var_getattr
    return super().var_getattr(tx, name)
  File "torch/_dynamo/variables/user_defined.py", line 958, in var_getattr
    ).call_function(tx, [], {})
  File "torch/_dynamo/variables/functions.py", line 383, in call_function
    return super().call_function(tx, args, kwargs)
  File "torch/_dynamo/variables/functions.py", line 322, in call_function
    return super().call_function(tx, args, kwargs)
  File "torch/_dynamo/variables/functions.py", line 106, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 810, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 2937, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 3053, in inline_call_
    tracer.run()
  File "torch/_dynamo/symbolic_convert.py", line 957, in run
    while self.step():
  File "torch/_dynamo/symbolic_convert.py", line 869, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 557, in wrapper
    return inner_fn(self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 1564, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "torch/_dynamo/symbolic_convert.py", line 804, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "torch/_dynamo/variables/nn_module.py", line 899, in call_function
    return variables.UserFunctionVariable(fn, source=source).call_function(
  File "torch/_dynamo/variables/functions.py", line 322, in call_function
    return super().call_function(tx, args, kwargs)
  File "torch/_dynamo/variables/functions.py", line 106, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 810, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 2937, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 3053, in inline_call_
    tracer.run()
  File "torch/_dynamo/symbolic_convert.py", line 957, in run
    while self.step():
  File "torch/_dynamo/symbolic_convert.py", line 869, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 557, in wrapper
    return inner_fn(self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 1642, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars)
  File "torch/_dynamo/symbolic_convert.py", line 804, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "torch/_dynamo/variables/lazy.py", line 156, in realize_and_forward
    return getattr(self.realize(), name)(*args, **kwargs)
  File "torch/_dynamo/variables/nn_module.py", line 899, in call_function
    return variables.UserFunctionVariable(fn, source=source).call_function(
  File "torch/_dynamo/variables/functions.py", line 322, in call_function
    return super().call_function(tx, args, kwargs)
  File "torch/_dynamo/variables/functions.py", line 106, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 810, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 2937, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 3053, in inline_call_
    tracer.run()
  File "torch/_dynamo/symbolic_convert.py", line 957, in run
    while self.step():
  File "torch/_dynamo/symbolic_convert.py", line 869, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 557, in wrapper
    return inner_fn(self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 1564, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "torch/_dynamo/symbolic_convert.py", line 804, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "torch/_dynamo/variables/functions.py", line 383, in call_function
    return super().call_function(tx, args, kwargs)
  File "torch/_dynamo/variables/functions.py", line 322, in call_function
    return super().call_function(tx, args, kwargs)
  File "torch/_dynamo/variables/functions.py", line 106, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 810, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 2937, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "torch/_dynamo/symbolic_convert.py", line 3053, in inline_call_
    tracer.run()
  File "torch/_dynamo/symbolic_convert.py", line 957, in run
    while self.step():
  File "torch/_dynamo/symbolic_convert.py", line 869, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 557, in wrapper
    return inner_fn(self, inst)
  File "torch/_dynamo/symbolic_convert.py", line 1564, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "torch/_dynamo/symbolic_convert.py", line 804, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "torch/_dynamo/variables/user_defined.py", line 493, in call_function
    return super().call_function(tx, args, kwargs)
  File "torch/_dynamo/variables/base.py", line 321, in call_function
    unimplemented(f"call_function {self} {args} {kwargs}")
  File "torch/_dynamo/exc.py", line 283, in unimplemented
    raise Unsupported(msg, case_name=case_name)
torch._dynamo.exc.Unsupported: call_function UserDefinedClassVariable(<class 'torchao.dtypes.affine_quantized_tensor.PlainAQTLayout'>) [TensorVariable(), TensorVariable(), TensorVariable(), UserDefinedObjectVariable(PlainLayoutType)] {}

from user code:
   File "torchao/torchao/_models/llama/generate.py", line 61, in decode_one_token
    logits = model(x, input_pos)
  File "torchao/torchao/_models/llama/model.py", line 141, in forward
    x = layer(x, input_pos, freqs_cis, mask)
  File "torchao/torchao/_models/llama/model.py", line 160, in forward
    h = x + self.attention(self.attention_norm(x), freqs_cis, mask, input_pos)
  File "torchao/torchao/_models/llama/model.py", line 193, in forward
    q, k, v = self.wqkv(x).split([self.dim, kv_size, kv_size], dim=-1)
  File "torch/nn/modules/linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
  File "torch/nn/utils/parametrize.py", line 407, in get_parametrized
    return parametrization()
  File "torch/nn/utils/parametrize.py", line 303, in forward
    x = self[0](*originals)
  File "torchao/torchao/utils.py", line 221, in forward
    rebuilt = tp.__tensor_unflatten__(inner_tensors, meta, None, None)
  File "torchao/torchao/dtypes/affine_quantized_tensor.py", line 417, in __tensor_unflatten__
    return cls(int_data, scale, zero_point, layout_type)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

**Comment by sanchitintel** [comment]
Attached logs with environment variables `TORCH_LOGS="+dynamo"` and `TORCHDYNAMO_VERBOSE=1`. Thanks!

This seems related -
```
V0805 15:11:33.053000 3215313 torch/_dynamo/symbolic_convert.py:878] [0/0] empty checkpoint
V0805 15:11:33.053000 3215313 torch/_dynamo/symbolic_convert.py:3067] [0/0] FAILED INLINING <code object __tensor_unflatten__ at 0x7f793545faa0, file "torchao/torchao/dtypes/affine_quantized_tensor.py", line 411>
V0805 15:11:33.053000 3215313 torch/_dynamo/symbolic_convert.py:878] [0/0] empty checkpoint
V0805 15:11:33.053000 3215313 torch/_dynamo/symbolic_convert.py:3067] [0/0] FAILED INLINING <code object forward at 0x7f79ef300660, file "torchao/torchao/utils.py", line 215>
V0805 15:11:33.054000 3215313 torch/_dynamo/symbolic_convert.py:878] [0/0] empty checkpoint
V0805 15:11:33.054000 3215313 torch/_dynamo/symbolic_convert.py:3067] [0/0] FAILED INLINING <code object forward at 0x7f7938c40a80, file "stock/torch/nn/utils/parametrize.py", line 295>
V0805 15:11:33.054000 3215313 torch/_dynamo/symbolic_convert.py:878] [0/0] empty checkpoint
V0805 15:11:33.054000 3215313 torch/_dynamo/symbolic_convert.py:3067] [0/0] FAILED INLINING <code object get_parametrized at 0x7f7938c40ea0, file "stock/torch/nn/utils/parametrize.py", line 387>
V0805 15:11:33.054000 3215313 torch/_dynamo/symbolic_convert.py:878] [0/0] empty checkpoint
V0805 15:11:33.054000 3215313 torch/_dynamo/symbolic_convert.py:3067] [0/0] FAILED INLINING <code object forward at 0x7f79393b0660, file "stock/torch/nn/modules/linear.py", line 124>
V0805 15:11:33.054000 3215313 torch/_dynamo/symbolic_convert.py:878] [0/0] empty checkpoint
V0805 15:11:33.054000 3215313 torch/_dynamo/symbolic_convert.py:3067] [0/0] FAILED INLINING <code object forward at 0x7f7935294a80, file "torchao/torchao/_models/llama/model.py", line 189>
V0805 15:11:33.054000 3215313 torch/_dynamo/symbolic_convert.py:878] [0/0] empty checkpoint
V0805 15:11:33.054000 3215313 torch/_dynamo/symbolic_convert.py:3067] [0/0] FAILED INLINING <code object forward at 0x7f7935294710, file "torchao/torchao/_models/llama/model.py", line 159>
V0805 15:11:33.054000 3215313 torch/_dynamo/symbolic_convert.py:878] [0/0] empty checkpoint
V0805 15:11:33.054000 3215313 torch/_dynamo/symbolic_convert.py:3067] [0/0] FAILED INLINING <code object forward at 0x7f7935294450, file "torchao/torchao/_models/llama/model.py", line 134>
V0805 15:11:33.054000 3215313 torch/_dynamo/symbolic_convert.py:878] [0/0] empty checkpoint
Traceback (most recent call last):
  File "torchao/torchao/_models/llama/generate.py", line 348, in <module>
    main(
  File "torchao/torchao/_models/llama/generate.py", line 271, in main
  ```

[llama3_dynamo_logs.zip](https://github.com/user-attachments/files/16503279/llama3_dynamo_logs.zip)

**Comment by jerryzh168** [comment]
hmm we were able to run these I think, it might be related to the pytorch version and torchao version you are using, could you install pytorch nightly and the latest version of torchao and run again?

**Comment by sanchitintel** [comment]
Thanks for confirming! Worked with the current PyTorch & the torchao repo HEADs.
Sorry for the inconvenience!

```
Versions of relevant libraries:
[pip3] torch==2.5.0a0+git72f2b29
[pip3] torchao==0.4.0+git433cd14
[conda] Could not collect
```
