### ISSUE TITLE
Repr of LinearActivationQuantizedTensor is broken

### ISSUE THREAD

**Issue by BenjaminBossan** [pytorch/ao#871]
I'm using torchao v0.4.0 and torch v2.4.1. To reproduce:

```python
from transformers import AutoModelForCausalLM, TorchAoConfig

model_id = "facebook/opt-125m"
quantization_config = TorchAoConfig("int8_dynamic_activation_int8_weight")
model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=quantization_config)
weight = model.model.decoder.layers[0].self_attn.v_proj.weight
repr(weight)
```

This raises the following error:

```
Traceback (most recent call last):
  File "/home/name/anaconda3/envs/peft/lib/python3.11/site-packages/torch/_tensor.py", line 459, in __repr__
    return handle_torch_function(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/anaconda3/envs/peft/lib/python3.11/site-packages/torch/overrides.py", line 1647, in handle_torch_function
    result = torch_func_method(public_api, types, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/anaconda3/envs/peft/lib/python3.11/site-packages/torchao/dtypes/utils.py", line 56, in _dispatch__torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/anaconda3/envs/peft/lib/python3.11/site-packages/torch/_tensor.py", line 463, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/anaconda3/envs/peft/lib/python3.11/site-packages/torch/_tensor_str.py", line 698, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/anaconda3/envs/peft/lib/python3.11/site-packages/torch/_tensor_str.py", line 618, in _str_intern
    tensor_str = _tensor_str(self, indent)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/anaconda3/envs/peft/lib/python3.11/site-packages/torch/_tensor_str.py", line 350, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/anaconda3/envs/peft/lib/python3.11/site-packages/torch/_tensor_str.py", line 384, in get_summarized_data
    start = [self[i] for i in range(0, PRINT_OPTS.edgeitems)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/anaconda3/envs/peft/lib/python3.11/site-packages/torch/_tensor_str.py", line 384, in <listcomp>
    start = [self[i] for i in range(0, PRINT_OPTS.edgeitems)]
             ~~~~^^^
  File "/home/name/anaconda3/envs/peft/lib/python3.11/site-packages/torchao/dtypes/utils.py", line 70, in _dispatch__torch_dispatch__
    raise NotImplementedError(f"{cls.__name__} dispatch: attempting to run unimplemented operator/function: {func}")
NotImplementedError: LinearActivationQuantizedTensor dispatch: attempting to run unimplemented operator/function: aten.select.int
```

**Comment by supriyar** [comment]
@jerryzh168 any idea what's going on here?

**Comment by jerryzh168** [comment]
@BenjaminBossan could you try again with 0.5? I just checked torchao 0.5 and torch nightly and `repr` runs

**Comment by BenjaminBossan** [comment]
Indeed this has been solved, thanks!
